#!/bin/bash

WDIR=${PWD}

cd ..
if [ -z ${ARMA_INCLUDE_PATH+x} ]; then 
    export ARMA_INCLUDE_PATH="$PWD/include"
fi
export CXXCOV=gcov
export LD_LIBRARY_PATH="$PWD":$LD_LIBRARY_PATH
cd tests

#

declare -a DIRS=("constrained" "misc" "unconstrained" "zeros")

for i in "${DIRS[@]}"; do
    cd "$WDIR"/"$i"

    ./configure -c
    make
    sh ./../test_setup/cov_check
done
